import { Course, DashboardData, Enrollment, Payment, User } from './types';

export const mockDashboardData: DashboardData = {
  stats: {
    totalStudents: 148,
    totalTeachers: 14,
    totalCourses: 18,
    totalEnrollments: 215,
    studentPayments: 48250,
    teacherPayments: 16800,
    remainingBalance: 9750,
  },
  recentAttendances: [
    {
      id: 'att-1',
      student: { fullName: 'أحمد محمود العلي' } as any,
      teacher: { fullName: 'د. سامر الحلبي' } as any,
      course: { name: 'برمجة الويب المتكاملة (Fullstack)' } as any,
      date: '2026-10-08',
      status: 'present',
    },
    {
      id: 'att-2',
      student: { fullName: 'سارة خالد النجار' } as any,
      teacher: { fullName: 'م. ريم القدسي' } as any,
      course: { name: 'تصميم واجهات وتجربة المستخدم (UI/UX)' } as any,
      date: '2026-10-08',
      status: 'present',
    },
    {
      id: 'att-3',
      student: { fullName: 'عمر ياسين حمود' } as any,
      teacher: { fullName: 'أ. طارق الشامي' } as any,
      course: { name: 'علوم البيانات والذكاء الاصطناعي' } as any,
      date: '2026-10-07',
      status: 'late',
    },
  ],
  recentGrades: [
    {
      id: 'grd-1',
      student: { fullName: 'أحمد محمود العلي' } as any,
      teacher: { fullName: 'د. سامر الحلبي' } as any,
      course: { name: 'برمجة الويب المتكاملة' } as any,
      title: 'امتحان منتصف الفصل',
      score: 95,
      maxScore: 100,
    },
    {
      id: 'grd-2',
      student: { fullName: 'ليلى هاني عثمان' } as any,
      teacher: { fullName: 'م. ريم القدسي' } as any,
      course: { name: 'تصميم واجهات وتجربة المستخدم' } as any,
      title: 'المشروع العملي الأول',
      score: 88,
      maxScore: 100,
    },
  ],
  recentNotifications: [
    {
      id: 'notif-1',
      title: 'بدء التسجيل للفصل الخريفي',
      message: 'نحيطكم علماً بافتتاح باب التسجيل في مسارات البرمجة المتقدمة.',
      createdAt: '2026-10-08T10:00:00Z',
    },
  ],
};

export const mockStudents: User[] = [
  {
    id: 'std-1',
    fullName: 'أحمد محمود العلي',
    role: 'student',
    primaryContact: '0933112233',
    phones: [{ number: '0933112233', label: 'شخصي' }],
    isActive: true,
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'std-2',
    fullName: 'سارة خالد النجار',
    role: 'student',
    primaryContact: '0944223344',
    phones: [{ number: '0944223344', label: 'واتساب' }],
    isActive: true,
    createdAt: '2026-09-03T09:30:00Z',
  },
  {
    id: 'std-3',
    fullName: 'عمر ياسين حمود',
    role: 'student',
    primaryContact: '0955334455',
    phones: [{ number: '0955334455', label: 'ولي الأمر' }],
    isActive: true,
    createdAt: '2026-09-10T11:15:00Z',
  },
  {
    id: 'std-4',
    fullName: 'مريم زياد الشريف',
    role: 'student',
    primaryContact: '0966445566',
    phones: [{ number: '0966445566', label: 'شخصي' }],
    isActive: true,
    createdAt: '2026-09-15T14:00:00Z',
  },
];

export const mockTeachers: User[] = [
  {
    id: 'tch-1',
    fullName: 'د. سامر الحلبي',
    role: 'teacher',
    primaryContact: '0911223344',
    phones: [{ number: '0911223344', label: 'رئيسي' }],
    isActive: true,
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'tch-2',
    fullName: 'م. ريم القدسي',
    role: 'teacher',
    primaryContact: '0922334455',
    phones: [{ number: '0922334455', label: 'شخصي' }],
    isActive: true,
    createdAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'tch-3',
    fullName: 'أ. طارق الشامي',
    role: 'teacher',
    primaryContact: '0933445566',
    phones: [{ number: '0933445566', label: 'عمل' }],
    isActive: true,
    createdAt: '2026-08-25T09:00:00Z',
  },
];

export const mockCourses: Course[] = [
  {
    id: 'crs-1',
    name: 'تطوير تطبيقات الويب المتكاملة (Fullstack Node & React)',
    code: 'WEB-101',
    description: 'دورة شاملة لبناء أنظمة ويب احترافية بتقنيات حديثة وقواعد بيانات.',
    level: 'intermediate',
    type: 'offline',
    price: 350,
    teacherCompensation: 120,
    schedule: 'الأحد والثلاثاء 4:00 - 6:00 م',
    durationWeeks: 12,
    teacher: 'د. سامر الحلبي',
    isActive: true,
  },
  {
    id: 'crs-2',
    name: 'تصميم تجربة وواجهة المستخدم المتقدمة (UI / UX)',
    code: 'DES-201',
    description: 'إتقان Figma ونظم التصميم والتفكير التصميمي وبناء نماذج تفاعلية.',
    level: 'beginner',
    type: 'online',
    price: 280,
    teacherCompensation: 100,
    schedule: 'السبت والإثنين 6:00 - 8:00 م',
    durationWeeks: 8,
    teacher: 'م. ريم القدسي',
    isActive: true,
  },
  {
    id: 'crs-3',
    name: 'علوم البيانات وتعلم الآلة (Data Science & ML)',
    code: 'AI-301',
    description: 'تحليل البيانات الضخمة، نماذج بايثون، والشبكات العصبية العميقة.',
    level: 'advanced',
    type: 'offline',
    price: 450,
    teacherCompensation: 160,
    schedule: 'الأربعاء والخميس 5:00 - 7:30 م',
    durationWeeks: 14,
    teacher: 'أ. طارق الشامي',
    isActive: true,
  },
];
